[aws]
aws-app ansible_host=3.231.27.202 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/aws_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[azure]
azure-vm ansible_host=13.68.190.21 ansible_user=azureuser ansible_password=YourSecurePassword123! ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[webservers:children]
aws
azure
